import os

from dotenv import load_dotenv
from openai import OpenAI

# Load environment variables
load_dotenv()


# Retrieve the OpenAI API key from the environment
api_key = os.getenv("OPENAI_API_KEY")


# Check that the API key was successfully loaded
# If the key does not exist, stop the program and display a useful error message
if not api_key:
    raise ValueError(
        "OPENAI_API_KEY was not found. "
        "Make sure it exists inside the .env file."
    )

# Create OpenAI client
client = OpenAI(api_key=api_key)

# Chatbot function
def chat_with_gpt(prompt):
    # Send the user's prompt to the OpenAI Responses API
    response = client.responses.create(
        model="gpt-5.6-terra",
        input=prompt
    )

    # Extract the text generated by the model and remove unnecessary whitespace
    return response.output_text.strip()

# Main program
if __name__ == "__main__":

    print("Chatbot started!")
    print("Type 'quit', 'exit', or 'bye' to stop the chatbot.\n")

    # Continue running the chatbot until the user enters one of the exit commands
    while True:

        # Ask the user for a message
        user_input = input("You: ")

        # Convert the input to lowercase before checking whether the user wants to exit
        if user_input.lower() in ["quit", "exit", "bye"]:
            print("Chatbot: Goodbye!")
            break

        try:
            # Send the user's message to the LLM
            response = chat_with_gpt(user_input)

            # Display the generated response
            print("Chatbot:", response)

        except Exception as error:
            # Prevent the whole program from crashing if something goes wrong with the API request.
            print("An error occurred while contacting OpenAI:")
            print(error)
