import os
from pathlib import Path

from dotenv import load_dotenv
from google import genai

# Get the directory containing this chatbot.py file.
current_directory = Path(__file__).resolve().parent

# Load environment variables
load_dotenv(current_directory.parent / ".env")


# Retrieve the Gemini API key from the environment
api_key = os.getenv("GEMINI_API_KEY")


# Check that the API key was successfully loaded
# If the key does not exist, stop the program and display a useful error message
if not api_key:
    raise ValueError(
        "GEMINI_API_KEY was not found. "
        "Make sure it exists inside the .env file."
    )

# Create Gemini client
client = genai.Client(api_key=api_key)

# Chatbot function
def chat_with_gemini(prompt):
    # Send the user's prompt to the Gemini
    interaction = client.interactions.create(
        model="gemini-3.6-flash",
        input=prompt
    )

    # Extract the text generated by the model and remove unnecessary whitespace
    return interaction.output_text.strip()

# Main program
if __name__ == "__main__":

    print("Chatbot started!")
    print("Type 'quit', 'exit', or 'bye' to stop the chatbot.\n")

    # Continue running the chatbot until the user enters one of the exit commands
    while True:

        # Ask the user for a message
        user_input = input("You: ")

        # Convert the input to lowercase before checking whether the user wants to exit
        if user_input.lower() in ["quit", "exit", "bye"]:
            print("Chatbot: Goodbye!")
            break

        try:
            # Send the user's message to the LLM
            response = chat_with_gemini(user_input)

            # Display the generated response
            print("Chatbot:", response)

        except Exception as error:
            # Prevent the whole program from crashing if something goes wrong with the gemini API request.
            print("An error occurred while contacting Gemini:")
            print(error)
